### ISSUE TITLE
Error while running GCAM

### ISSUE THREAD

**Issue by PoonamNK** [vancegroup/lua-voce#13]
Hi,

I have been using GCAM for the last 3 years but recently I changed my laptop, still working on Windows. After installing all the required software such as Java 8u221 (64 bit), Microsoft visual c++, having a RAM of 16GB and having jvm.dll files at two locations (System32 and SysWow64), I am getting the following error while running the model. 

**Error occurred during initialization of VM
Unable to load native library: Can't find dependent libraries
Press any key to continue...** 

What could be the possible issue?

Thanks and regards,
Poonam

**Comment by emuwren2003** [comment]
What was the resolution for this error?
